### ISSUE TITLE
Warning on link to broom\augment documentation in r-patched-linux-x86_64

### ISSUE THREAD

**Issue by dmenne** [tidymodels/broom#1017]
In my [code documentation](https://github.com/dmenne/breathtestcore) , I have used

`\code{\link[broom]{augment}}`

which has passed CRAN checks for years and still passes is it for the current version of R.

However, in `r-patched-linux-x86_64` I get [a warning](https://cran.r-project.org/web/checks/check_results_breathtestcore.html):

`file link ‘augment’ in package ‘broom’ does not exist and so has been treated as a topic`

(similar for tidy).

Is this a broom problem (no generic augment documented?) or what can I do with my code to correct this?

**Comment by alexpghayes** [comment]
I suspect this is because we re-export `augment()` (and `tidy()` and `glance()` generics from the `generics` package). I *think* the solution is to replace `\code{\link[broom]{augment}}` with `\code{\link[generics]{augment}}` if you want documentation for the S3 generics. @DavisVaughan should know more

**Comment by dmenne** [comment]
Thanks, that looks good.
