### ISSUE TITLE
"mediate" class used by different packages - so tidy.mediate fails in hard to interpret way

### ISSUE THREAD

**Issue by LukasWallrich** [tidymodels/broom#1037]
I just tried to tidy a `psych::mediate()` output, which fails with a very uninformative error about columns being NULL rather than vectors. Looking at the documentation, it becomes clear that this is because `tidy.mediate()` intends to work on `mediation::mediate()` objects. 

However, might it be worthwhile to fail with an informative error? The `psych::mediate()` objects also have class `psych` so that disambiguation would be straightforward. Is there a standard broom policy to deal with this kind of situation? Then I'd be happy to submit a PR to save other people the time I just wasted on this :)

**Comment by simonpcouch** [comment]
Ah, thanks for dropping a note here! Very helpfully phrased, as well. :-)

The usual strategy would be to set `tidy.psych <- tidy.default`, as the class of those `psych::mediate` models is `[1] "psych"   "mediate"`, except that `broom` already supports output from `psych::cohen.kappa` which has class `[1] "psych" "kappa"`. Because `psych` switches its subclassing order from that used in S3 dispatch, I think we'll need to instead come up with a quick check inside of `tidy.mediate` to detect `psych` objects and throw an error.
