### ISSUE TITLE
p-value unavailable for svy.olr function: is there an alternative way?

### ISSUE THREAD

**Issue by paige-cho** [tidymodels/broom#1140]
Hello!

tidy for svyolr is a wonderful function with many advantages.
However, for use in scientific reporting, the very essential element is unavailable, p-value.
Are there any ways to extract p-values from svy.olr model with tidy function?
Thanks so much for developing this wonderful package.

Paige

**Comment by simonpcouch** [comment]
Thank you for the issue, and for the kind words on broom!

Note that the summary method for these objects doesn't include p-values:

``` r
library(broom)
library(survey)
#> Loading required package: grid
#> Loading required package: Matrix
#> Loading required package: survival
#> 
#> Attaching package: 'survey'
#> The following object is masked from 'package:graphics':
#> 
#>     dotchart

data(api)
dclus1 <- svydesign(id = ~dnum, weights = ~pw, data = apiclus1, fpc = ~fpc)
dclus1 <- update(dclus1, mealcat = cut(meals, c(0, 25, 50, 75, 100)))

m <- svyolr(mealcat ~ avg.ed + mobility + stype, design = dclus1)

summary(m)
#> Call:
#> svyolr(mealcat ~ avg.ed + mobility + stype, design = dclus1)
#> 
#> Coefficients:
#>               Value Std. Error   t value
#> avg.ed   -2.6999217 1.13422434 -2.380412
#> mobility  0.0325042 0.02065336  1.573797
#> stypeH   -1.7574715 0.69953393 -2.512346
#> stypeM   -0.6191463 0.30964416 -1.999541
#> 
#> Intercepts:
#>                  Value   Std. Error t value
#> (0,25]|(25,50]   -8.8579  3.6862    -2.4030
#> (25,50]|(50,75]  -6.5865  3.1089    -2.1186
#> (50,75]|(75,100] -4.9249  2.8634    -1.7200
#> (26 observations deleted due to missingness)
```

This is because the asymptotics on a test a la `Pr(>=|t|)` (as would be included with `summary(svyglm(...))` output and friends) are a bit tricky here—more on this in the documentation for `survey::regTermTest()` and [Lumley's book about the package](http://r-survey.r-forge.r-project.org/svybook/). 

If folks with expertise here are interested in improving these tidiers, I'd welcome further discussion and PRs, though it's unlikely this will come to the top of my to-do list. :)

Related to #1107.

**Comment by simonpcouch** [comment]
Thanks again for the issue! Given that this hasn't come to the top of the to-do list in the last month, I'm going to go ahead and close.
