### ISSUE TITLE
re-upping discussion of tobit model tidiers

### ISSUE THREAD

**Issue by bbolker** [tidymodels/broom#1167]
As discussed on [Stack Overflow](https://stackoverflow.com/questions/76770110/how-to-use-broomtidy-for-tobit-models) and on [this closed issue](https://github.com/tidymodels/broom/issues/749), there's not currently a tidier for `tobit` models (from the `AER` package). ([This commit](https://github.com/tidymodels/broom/commit/56437bce30841211bfa64074677fe2d9124d99cc) "solved" the problem of an obscure error message by setting `tidy.tobit <- tidy.default`, which leads to an interpretable rather than an uninterpretable error message).  This appears to be solvable by a small workaround:

```r
tidy.tobit <- function(x, ...) {
   class(x) <- "survreg"
   tidy(x, ...)
}
```

Example:

```r
data("Affairs", package = "AER")
# model
m1 <-
  AER::tobit(affairs ~ age + yearsmarried + religiousness + occupation + rating,
             data = Affairs)
tidy(m1)
```

The reason this works is that the `tidy.survreg` tidier depends on the output of `summary()` having a `$table` component.  `AER::summary.tobit()` does **not** have such a component, but `survival::summary.survreg` does ...

**Comment by simonpcouch** [comment]
Thanks for documenting the current state of these tidiers + a workaround! Saw that SO post this morning—I'm glad your effort is findable on the repo now, too.

With an eye for the [maintenance guidelines](https://broom.tidymodels.org/articles/maintenance.html#guidelines) of the package, we won't be merging in support for these model objects. I appreciate you bringing this up, though.

The answer re: your note on the SO post:

> _(I don't know why it doesn't use standard S3 inheritance rules?)_

is in your issue description here. `AER::tobit` output dispatches to the survreg tidier but still has subclass `tobit`, resulting in the error on the issue you've linked:

``` r
# tidier from 2019 and before
broom::tidy(m1)
#> Error in if (!is.null(newnames) && length(newnames) != ncol(x)) {: missing value where TRUE/FALSE needed
```

We set that method for the subclass so that users get a more informative error.

**Comment by bbolker** [comment]
Thanks.  I think I realized the answer to my question partway through composing the issue but failed to update the SO post.
