### ISSUE TITLE
Support for Arima x13 seasonal adjusment funtions via package seasonal

### ISSUE THREAD

**Issue by gustavorubim** [tidymodels/broom#176]
library(seasonal)
a <- (a ts object)
  b <- seas(a) 

broom::tidy(b)
Error in as.data.frame.default(x) : 
  cannot coerce class ""seas"" to a data.frame
In addition: Warning message:
In tidy.default(b) :
  No method for tidying an S3 object of class seas , using as.data.frame
>

**Comment by christophsax** [comment]
I added an experimental `data.frame` argument to `summary.seas` in seasonal 1.4, which is now on CRAN. This gives you what you would get with `broom::tidy`.

But I see it would be probably nicer to implement an `as.data.frame` method, so the default tidy method would work as well, without a need for specific broom methods.

**Comment by alexpghayes** [comment]
Hey @christophsax I just read christophsax/seasonal#192. It looks like you have some nice `tidy` implementations already -- we're actually starting to encourage people to implement `tidy`, `glance` and `augment` in modelling packages themselves rather than `broom`. Would you be willing to do that with `seasonal`?

When people do this there's a bit of fun registering methods in case `broom` also gets loaded. We could help out with that if you're interested.

**Comment by christophsax** [comment]
Is it possible to do that without the need to `Imports` broom? `Suggests` would be fine.

No problem to that, but it may take a little while.

**Comment by alexpghayes** [comment]
It is. Planning to add some resources on how to do this in the next couple days, will let you know when I put them up.
