### ISSUE TITLE
Request for broom to work with scam package

### ISSUE THREAD

**Issue by SimonCoulombe** [tidymodels/broom#186]
The scam package is an extension of the mgcv package, which adds the ability to constrain the shape of the splines (for example, they can be forced to be monotonously increasing).

**Comment by bkmontgom** [comment]
Me too.  This would be a great addition.  The structure of the scam model is similar to gam.

**Comment by IndrajeetPatil** [comment]
@simonpcouch This is currently not supported in `broom`, but since the class of the object is `glm`/`lm`, those tidiers are called.

``` r
library(scam)
#> Loading required package: mgcv
#> Loading required package: nlme
#> This is mgcv 1.8-31. For overview type 'help("mgcv-package")'.
#> This is scam 1.2-5.
set.seed(0)

n <- 200
x1 <- runif(n) * 6 - 3
f1 <- 3 * exp(-x1^2) # unconstrained term
f1 <- (f1 - min(f1)) / (max(f1) - min(f1)) # function scaled to have range [0,1]
x2 <- runif(n) * 4 - 1
f2 <- exp(4 * x2) / (1 + exp(4 * x2)) # monotone increasing smooth
f2 <- (f2 - min(f2)) / (max(f2) - min(f2)) # function scaled to have range [0,1]
f <- f1 + f2
y <- f + rnorm(n) * 0.1
dat <- data.frame(x1 = x1, x2 = x2, y = y)

## fit model, results, and plot...
b <- scam(y ~ s(x1, k = 15, bs = "cr", m = 2) + s(x2, k = 25, bs = "mpi", m = 2),
  family = gaussian(link = "identity"), data = dat, not.exp = FALSE
)

class(b)
#> [1] "scam" "glm"  "lm"

broom::tidy(b)
#> Error: Join columns must be present in data.
#> x Problem with `term` and `estimate`.
```

<sup>Created on 2020-06-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by simonpcouch** [comment]
Thanks for noting this, @IndrajeetPatil! I'm currently assigning the `default` tidier methods to `scam` objects so that they will error more informatively.

We’ve decided that, in general, we won’t be adding new tidier methods to broom after the upcoming 0.7.0 release in favor of asking the model-owning package (in this case, scam) to write and export the tidiers. We’ve written some [documentation](https://www.tidymodels.org/learn/develop/broom/) on how to make this happen and have also provided a much lighter-weight dependency than broom, `r-lib/generics`, to supply the tidier generics. We'll keep that tidymodels.org article linked above up to date with current resources to help in the process. If the `scam` package ends up being able to supply those methods, let us know and we'll deprecate these new ones so there aren't namespace conflicts.🙂
