### ISSUE TITLE
Mixed models

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#329]
Hey @bbolker:

Dave and I were talking this afternoon and we're hoping that `broom.mixed` can take over as a specialized package for tidying mixed models. Ideally we would deprecate the `lme` and `rstanarm` families of tidiers currently in `broom` in favor of `broom.mixed` for the upcoming `broom 0.5.0` release in early July. We'd prefer that `broom.mixed` be on CRAN before deprecating, however.

We're wondering about the following:

- What you think about moving tidiers fully out of `broom` and into `broom.mixed`?
- The current status of `broom.mixed`. Is it basically usable or are there major bugs, etc?
- What kind of assistance would you need to get `broom.mixed` on CRAN?
- What are key components of `broom` that `broom.mixed` will import/rely on? What do we need to do make them as robust as possible?

**Comment by bbolker** [comment]
- I'm fine with moving the tidiers into `broom.mixed`
- `broom.mixed` is basically usable. In particular, it's at least as good (if I recall correctly) as the current functionality in `broom`. The main issues I want to clear up before releasing are various API changes that it would be much better to make sooner (before `broom.mixed` is released) rather than later. That way, people can deal with the changes when they switch those tidying operations from `broom` to `broom.mixed`. Most of the issues are about 

- improving the Bayesian (`MCMCglmm` and `brms`) tidiers and making them consistent with the other tidiers;
- changing some argument/option names to be more general

Probably the main assistance is in testing and discussion of options. (I would probably announce it on r-sig-mixed.)  

I'm not actually using a huge amount of `broom` infrastructure (the only functions I'm importing besides `glance`/`tidy`/`augment` are `augment_columns` and `fix_data_frame`, and I've been gradually moving away from using the latter ...) 

#38 discusses some things I've thought about.

Probably my main request would be to deprecate the `exponentiate` argument, and replace it with a `transform` or `backtransform` argument (or add a `scale` argument that could be `link` or `response`) ...

**Comment by larmarange** [comment]
Just one comment regarding the `exponentiate` argument. It would be relevant that this argument remains consistent between `broom` and `broom.mixed`, in particular for generic functions using `tidy` method (for example `ggcoef` function in `GGally`: https://ggobi.github.io/ggally/#ggallyggcoef)

**Comment by bbolker** [comment]
A couple of further thoughts on `exponentiate`.  While I think I prefer some more general kind of `transform` argument, it occurred to me that `exponentiate` is more broadly useful than I thought; it's *predictions* that have a broad range of scales (depending on whether the link function is logit, probit, cloglog, etc.); in contrast, for most modeling frameworks the only back-transformation of *parameters* you want is exponentiation (i.e. to get odds ratios from log-odds when `link="logit"` or hazard ratios from log-hazard ratios when `link="cloglog"`.  So maybe this doesn't need to be changed.  (Would still like to hear broader discussion, though ...)  The only counterexample I can think of is when a *single* zero-inflation parameter is estimated, and we might want to logistic-transform it to get a zero-inflation probability ...

**Comment by alexpghayes** [comment]
There are also some changes coming to `broom` that would be good to mirror in `broom.mixed`. Notably, we're more strictly defining the behavior of tidiers (see the [adding tidiers vignette](http://broom.tidyverse.org/articles/adding-tidiers.html) for a start) and I'll be writing tests to enforce these behaviors. All tidiers will begin returning tibbles by July 2, which may break a fair amount of code.

We'd like to keep the behavior of broom extensions consistent with broom and will be thinking about ways to make this work. I should have more information next week.

I hear you on changing argument and output column names to make them more general. I'd like to define a list of accept columns/argument names and include those in my tests. I know Dave is somewhat concerned about backwards compatibility with column names in particular. Maybe that's an issue for a separate thread?

**Comment by dgrtwo** [comment]
I think your re-thoughts on exponentiate are correct: I originally liked the idea of a link method but I can't think of useful link methods besides exponentiation.

We're planning a CRAN release of broom 0.5.0 for 2018-07-02 (it's a hard deadline because of [package check messages](https://cran.r-project.org/web/checks/check_results_broom.html)). Do you think you'll have broom.mixed on CRAN before then?

* If so we'd love to add warnings to our mixed model tidiers saying that they should install broom.mixed instead (we'd then turn these into errors in 0.6.0). 
* If not, we can wait for the next version to do the "handoff" of mixed model tidiers

Let us know your preferred timeline!

**Comment by bbolker** [comment]
I'm torn. I'd really like to get the API issues/revisions sorted out before then - that's the only thing I consider release-critical.  (It *might* be OK to release before that, but I'd really prefer not to.) Anything else is more wish-list material -- AFAIK there's nothing that the current release of broom does that broom.mixed *doesn't* do ...

Maybe I can try to get a rough cut on those in the very near future.  Since there are no official downstream packages to test for broom, the CRAN submission process should (???) be fairly straightforward ...

**Comment by alexpghayes** [comment]
My understanding of the interface issues, gathered all together into one place:

1. There are argument names that should be more general

I'm in the process of gathering argument and column names into a [glossary](http://broom.tidyverse.org/articles/adding-tidiers.html#glossary). It's currently incomplete and somewhat a low priority -- any argument name changes will be breaking and so any major revision of these on the broom side is probably a release out. If there are argument names that we need to discuss for `broom.mixed`, please let us know. Currently I only know of `exponentiate` (above) and `conf.low`/`conf.high` (#291) as discussion items.

2. Renaming `exponentiate` or adding a `scale` argument

I'm happy to follow whatever your recommendation is provided Dave is on board. It seems like the discussion above is leaning in the direction of keeping `exponentiate` with no changes?

3. Random effects tidying behavior needs to be defined re: #38 
4. Profile confidence intervals for mixed models

I think these are `broom.mixed` specific, and I'm sure that whatever happens with random effects tidying with be reasonable. My only request is that argument names for the `tidy` method line up with terms in the `Glossary` as much as possible, but again, this is probably a release out. Having one release cycle with argument names that are out of sync is okay with me because moving mixed models out of broom is a big win.

5. HDP intervals or quantiles for Bayesian tidiers

I'm happy with either of these, we just need to document the choice.


Getting a rough cut of `broom.mixed` onto CRAN would be fantastic since it would let us start deprecating mixed model tidiers and shrinking our codebase down to something more manageable.

**Comment by bbolker** [comment]
I'm not entirely happy with the state of broom.mixed, but I'd be willing to submit it to CRAN tomorrow if you want. I don't know if I've left it too late for you to deprecate the mixed-model stuff.

The main reason I would hesitate is that the `MCMCglmm` tidiers are pretty embryonic. But given that these aren't in broom at all, I think that's really a wish-list item.

Let me know ...

**Comment by alexpghayes** [comment]
The CRAN rush has actually been somewhat delayed. We've pretty much frozen `broom 0.5.0` and are giving revdep maintainers till July 16 to fix and revdep errors before we submit. We haven't deprecated mixed model/Bayesian tidiers yet, and plan to do that in the `broom 0.7.0` release, which will be at the end of the summer at the earliest.

In retrospect, `broom.mixed` would have had to have been on CRAN mid-June to get revdeps dealt with in time for the release, so that was a bit of a pipe dream. But we are looking forward to seeing `broom.mixed` on CRAN sometime soon! With any luck the discussion at bbolker/broom.mixed#22 will reveal that there's less that needs to be done than originally imagined.

**Comment by bbolker** [comment]
It does look like `MCMCglmm` is handled by `tidybayes` - that was the main thing I really wanted to do that I hadn't done yet. I'll have to start the #22 conversation and sees what happens ... maybe `broom.mixed` will be only *frequentist* mixed-model tidiers (`nlme`, `lme4`, `glmmTMB`, `glmmADMB`)? (I'd like to tidy `INLA` too, but that could turn out to be a big nuisance ... `INLA` is Bayesian but not sampling-based ...)

**Comment by alexpghayes** [comment]
I wouldn't be surprised if INLA tidying moves into `tidybayes` as well eventually, although I'm not entirely in the know. It seems likely to me that the Stan community officially or unofficially adopts `tidybayes`, and there's some overlap between the Stan and INLA communities if I recall correctly.

**Comment by bbolker** [comment]
close?

**Comment by IndrajeetPatil** [comment]
Will `broom 0.5.1` completely get rid of `merMod` tidiers since `broom.mixed` has been on `CRAN` for a while now and `broom 0.5.0` did warn users of the upcoming deprecation of `merMod` tidiers?

There is a risk of method registrations producing unexpected behavior (e.g., 
https://github.com/tidymodels/broom/issues/541), which would be minimized earlier than later. 

This should also get rid of the `warnings` with `r-devel`:
```r
Registered S3 methods overwritten by 'broom.mixed':
  method         from 
  augment.lme    broom
  augment.merMod broom
  glance.lme     broom
  glance.merMod  broom
  glance.stanreg broom
  tidy.brmsfit   broom
  tidy.gamlss    broom
  tidy.lme       broom
  tidy.merMod    broom
  tidy.rjags     broom
  tidy.stanfit   broom
  tidy.stanreg   broom
```

**Comment by alexpghayes** [comment]
No, it will not. I'm going to wait until it's not finals period to make breaking changes. But getting a new release out is slowly moving up my priority list.

**Comment by IndrajeetPatil** [comment]
Any idea when the next release of `broom` is scheduled? 

A lot of new changes have been made since the last major release `0.5.0` and I have to keep suppressing my tests that rely on these new changes because I rely on the `CRAN` version of `broom` for tests. Plus, there is also the issue of unwanted interactions between shared `broom` and `broom.mixed` tidiers, which can become problematic as they increasingly diverge from each other.

**Comment by alexpghayes** [comment]
I hear ya and I'm sorry I'm so behind. I'm targetting early to mid summer.
The big task for a CRAN release will be getting modeltests cleaned up and
onto CRAN.

I was hoping to have this all done by now but first year coursework makes
development a low priority until classes get out.
