### ISSUE TITLE
Does augment.garch make sense?

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#401]
Input a time series and get a data frame out? Going to put on hold for after `0.5.0`.

**Comment by wilsonfreitas** [comment]
I believe that that's the purpose of using broom, end up with a dataframe.
Maybe garch is more appropriate for another package like sweep or a specific one to handle garch models, since the majority of garch implementations don't handle dataframes directly.

Here is an example of how augment.garch makes things easier while tidier.

```r
library(magrittr)
library(ggplot2)
library(tseries)

data(EuStockMarkets)
dax <- diff(log(EuStockMarkets))[,"DAX"]

augment(dax.garch, dax) %>% ggplot(aes(x = .time, y = data)) +
  geom_line(colour = "black") +
  geom_line(aes(y = .fitted * 2.32), colour = "red")

smp1 = window(dax, end = c(1997, frequency(dax)))
smp2 = window(dax, start = c(1998, 1))
dax.garch <- garch(smp1)
augment(dax.garch, newdata = smp2) %>% ggplot(aes(x = .time, y = newdata)) +
  geom_line(colour = "black") +
  geom_line(aes(y = .fitted * 2.32), colour = "red")
```

**Comment by alexpghayes** [comment]
I totally agree that this is useful functionality. Mainly was thinking about how to deal with time series objects when validating augment input. I like the idea of moving this kind of stuff into `sweep`. Let me do a little more investigation and talk with Dave about that.
