### ISSUE TITLE
add attributes to objects to document metadata like conf.method, conf.level etc.?

### ISSUE THREAD

**Issue by bbolker** [tidymodels/broom#491]
It occurs to me that there is various metadata associated with tidy objects that is not preserved. For example, if we output from `tidy` with `conf.low` and `conf.high` columns, we don't know (1) what confidence level was used, (2) what confidence method (e.g. Wald vs profile) was used ... similarly with lots of options (e.g. `exponentiate`). I don't know what the tidyverse thinks about attributes, but that feels like it would be a simple/natural way to include this information.  

The very simplest thing would be to include the function call as an attribute (that should have all of the meta-data, although in very obscure cases it could lose information [e.g. someone calls `tidy()` with a `conf.level` argument that is itself a symbol, which turns out not to be evaluatable once the original evaluation environment has been discarded ... in this case it would make more sense to `eval()` the arguments before storing them. But maybe it's not worth worrying about such edge cases yet?)

**Comment by alexpghayes** [comment]
I think `tidymodels` is planning on embracing attributes a more fully for things like this. Perhaps @topepo can speak to this?

I'd prefer an attribute like `conf.method` with a value of `"Wald"` or `"profile"` to storing a function call, which I think is a bit opaque. Actually, this would probably be a good standard to institute across `tidymodels`.

This seems like a nice aspirational goal for broom, but since it'll require going through every tidier it's almost certainly going to have wait until someone is doing full time development.

**Comment by topepo** [comment]
I would suggest saving the `level` and `method` values as attributes.
