### ISSUE TITLE
Remove the demon scourge from tidy() that is `quick`

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/broom#678]
I know @dgrtwo likes it but I've never seen it used in the wild and it adds a lot of boilerplate code that I think new contributors find confusing. The easiest way to catch this is to update the allowed tidy argument list in `modeltests`.

**Comment by IndrajeetPatil** [comment]
Is this going to be hard-deprecated from `0.7.0`?

**Comment by alexpghayes** [comment]
Yeah. Unless revdep checks explode.

**Comment by IndrajeetPatil** [comment]
Since you are planning to make this big change for the next release, I am wondering if you think it will be worth it to also change the default value for `conf.int` argument from `FALSE` to `TRUE`? Or there are good reasons to retain this default?

I always want to see confidence intervals for the estimates so this seems straightforward to me, but maybe there are reasons - other than backward compatibility - that make `FALSE` a sensible default?

**Comment by alexpghayes** [comment]
Calculating confidence intervals can be quite computationally expensive.

**Comment by IndrajeetPatil** [comment]
I see. Got it.

**Comment by MatthieuStigler** [comment]
Hi Alex and Indrajeet

Sorry, did I understand correctly that you intend to remove the `quick` argument in future versions of broom? I that's the case, that would seem a big drawback to me. There are a bunch of applications where one is only interested in coefficients (like the bootstrap), not standard errors, and these applications are usually computer intensive (like bootstrap). Being able to use `quick=TRUE` can save a lot of time in this, so that option seems crucial to me. As an example, the bootstrap example you have in the vignette would run twice faster using `quick=TRUE` and for larger problems (mtcars has 32 obs...) gains could be even more significant. 

And if I misread your point and you are not thinking of removing that option, then please discard that whole comment (yet add `quick=TRUE` in the bootstrap vignette ;-))

Thanks!

**Comment by alexpghayes** [comment]
Removing the `quick` argument was my intention. This is because a `quick` argument often leads to some sort of internal helper for tidying methods (typically called `process_*`), and these have been messy and unpleasant to maintain. If we get rid of `quick`, tidying logic can live directly in `tidy`.

The reason I was comfortable with removing `quick` is because I have never once seen someone use `quick = TRUE` in the wild. Perhaps some more community feedback is necessary. I'll create a poll on Twitter in the next day or so.

If the issue is quickly getting point estimates only, I am tempted to suggest using `coef()`. There has been some suggestion of creating a separate generic to get regression coefficients only in #105, which I would now generalize to mean point estimates.

**Comment by alexpghayes** [comment]
This happened at some point. I plan to discuss this in more detail in the release notes, and am also considering a tidy version of `coef()` as a replacement. However, I believe this would need to be a new verb, rather than an argument to `tidy()` itself. In the short term, I'm going to point people toward using `tibble::enframe(coef(model_object))`.

I am sorry for inconveniences caused by this, but this change *dramatically* improves readability and maintainability.

**Comment by MatthieuStigler** [comment]
Oh this is sad news. The argument `quick=TRUE` was enabling *dramatic* improvements in speed when only the coefficients where needed, such as bootstrap, monte-carlo, cross-validation etc. 

So I would strongly support the idea of adding another verb/functionality to replace that feature :-)

**Comment by alexpghayes** [comment]
There's some discussion of this in #105. If you pitch a design idea, things will happen much faster!
