### ISSUE TITLE
Rename by_class argument to by.class in tidy.confusionMatrix()

### ISSUE THREAD

**Issue by IndrajeetPatil** [tidymodels/broom#750]
This change will not be back-compatible, but to follow the current naming convention of `broom`, this argument should be renamed to `by.class`-

https://github.com/tidymodels/broom/blob/af8a7161dcc0d3acf7f357ed53b4baea3cf0e0c3/R/caret-tidiers.R#L53

**Comment by alexpghayes** [comment]
Also update the argument glossary in `modeltests`.

**Comment by simonpcouch** [comment]
Are we still feeling this is worth the breaking change? There are a few instances of underscores elsewhere in [the modeltests glossaries](https://github.com/alexpghayes/modeltests/tree/master/data-raw).

**Comment by IndrajeetPatil** [comment]
But the `modeltests` functions are not user-facing, are they? 

I don't think we don't need so concerned about minor syntax inconsistencies across functions in that package, but we should think about it in the context of `broom` since a lot of people are bound to run into them. Or that's my two cents.

**Comment by simonpcouch** [comment]
The modeltests glossaries are based on functions found in broom--those glossaries show us that there are other instances of underscores in argument names throughout broom.

I agree that it'd be preferable if this argument had always had a period rather than an underscore. I'm personally more concerned about users' existing code breaking than new users needing to check the help-file/tooltip to see that this argument uses an underscore rather than a period.

**Comment by IndrajeetPatil** [comment]
I see. Yeah, breakage is a valid concern.

In that case, I will close this since I don't think a breaking change here is worth the benefit of consistency.
