### ISSUE TITLE
tidy() in R 3.6.1 produces 'Error in . [[object]][[1]] : subscript out of bounds', in R 3.4.4 it works fine 

### ISSUE THREAD

**Issue by istvan60** [tidymodels/broom#796]
When excecuting the following code in R 3.6.1 tidy() produces an odd error, which does not come up when R 3.4.4 is used. Broom version is the same in both cases; 0.5.2.

Here is the input data: [regr_test_16-18_havi_transect.txt](https://github.com/tidymodels/broom/files/3929697/regr_test_16-18_havi_transect.txt)

The error is:
![image](https://user-images.githubusercontent.com/20128185/70284656-0817e000-17c5-11ea-8b38-bea6b940de4b.png)

and the code:

```library(plyr)
library(dplyr)
library(data.table)
library(broom)
library(ggplot2)

name="regr_test_16-18_havi_transect"
adat=read.table(file=paste(name,".txt", sep=""), sep=";", header=T)
names_elev=c("Postojna", "Ljubljana-reaktor","Kredarica", "Zgornja_Radovna", "Rateče", "Seeberg", "Villacher_Alpe")
elev <- subset(adat, Name %in% names_elev)
adat2=elev
predictor="elev"
RMSElist=list()
datalist = list()
DData=melt(adat2,id=c("Name","elev", "POINT_X", "POINT_Y", "NEAR_DIST_geodesic"))
colnames(DData)<-c("Name","elev", "POINT_X", "POINT_Y", "NEAR_DIST_geodesic","month","d18O")

f <- as.formula(paste("d18O", paste(predictor), sep = " ~ "))


DData_NAn=DData %>% 
	group_by(month) %>% 
	filter(!all(is.na(d18O)))
	

dTlinreg = DData_NAn %>%
    group_by(month) %>%
    do(fitisotope=lm(f,data=.))

dTlinregCoef = tidy(dTlinreg, fitisotope)
dTlinregCoef

**Comment by alexpghayes** [comment]
I can't reproduce an error using your code. Can you make a [reprex](https://github.com/tidyverse/reprex)? In general, `broom` does not support operations on `data.frames`, and since you have created `dTlinreg` with `do()` that should be a `data.frame`. Please see https://broom.tidyverse.org/articles/broom_and_dplyr.html for the currently recommended `map` workflow.

**Comment by MysticChess** [comment]
I am experiencing the same issue for months, and I have now figured out the new version is somehow giving problems when the processed dataframe contains columns formatted as factor (in my case with specific levels). My current workaround is to convert the factor columns to character format, which works fine. It would be nice if that bug was fixed though, I do not like having to remove the levels of my columns and putting them back afterwards for plotting purposes.

**Comment by alexpghayes** [comment]
Can you provide a [reprex](https://reprex.tidyverse.org/)? Without a code sample this will be hard to debug.

**Comment by MysticChess** [comment]
Hello,

Thanks for your reaction, 

I have already tried giving a reprex but I could not make it. The point is when I save the data and load it again the error does not occur anymore (see attached screenshot of my console).

It seems to have something to do with the dataframe class itself, the one failing having also the tibble class, while the one working fine is a pure dataframe.

Is this enough information for you to look into it? I am not sure how I could provide you my data otherwise. Maybe with my R environment?

![broom_reprex](https://user-images.githubusercontent.com/63645268/79301915-169ca380-7eeb-11ea-9763-a153093c3100.PNG)

**Comment by FilipAgatic** [comment]
Hi, 

I had the same error when one of the factor levels was not present in the data, but it worked fine when I dropped that level completely. I recreated the error using the iris data set for a reproducible example: 

library(broom)
library(dplyr)

# Use the original iris dataset to group by species and run a model
fit <- iris %>% group_by(Species) %>% 
      do(model = lm(Petal.Length ~ Petal.Width,  data = .)) %>%
      tidy(model)

# Remove one of the species from the data set
irisReduced <- iris[iris$Species != "setosa",]
# Run the model again, but this time I get an error
fit2 <- irisReduced %>% group_by(Species) %>% 
      do(model = lm(Petal.Length ~ Petal.Width,  data = .)) %>%
      tidy(model)
#> Error in .[[object]][[1]]: subscript out of bounds
# Taking a look at the species column levels 
str(iris$Species)
#>  Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...
str(irisReduced$Species)
#>  Factor w/ 3 levels "setosa","versicolor",..: 2 2 2 2 2 2 2 2 2 2 ...

# Dropping the unneeded species level
irisReducedBetter <- droplevels(irisReduced)
str(irisReducedBetter$Species)
#>  Factor w/ 2 levels "versicolor","virginica": 1 1 1 1 1 1 1 1 1 1 ...
# running the same model again on a properly reduced dataset works.
fit3 <- irisReducedBetter %>% group_by(Species) %>% 
      do(model = lm(Petal.Length ~ Petal.Width,  data = .)) %>%
      tidy(model)

I hope this helps.

**Comment by simonpcouch** [comment]
Thanks for the additional information!

As of version 0.7.0, `data.frame` tidiers are now deprecated. You'll want to `purrr::map` on the `model` column in those dataframes. :-)
