### ISSUE TITLE
Adding n (sample size) as an option

### ISSUE THREAD

**Issue by lrose1** [tidymodels/broom#872]
I think it would be very useful to include the n for the model in either tidy() or glance(). Having to add it manually as in [this SO example](https://stackoverflow.com/questions/61417205/extract-model-sample-sizes-using-broom-in-r) is a bit of a pain, and the n is often what is needed for an output table. In tidy.lm, this would be a simple, but not sure about the others.

```r
library(broom)

fit <- lm(Sepal.Width ~ Petal.Length + Petal.Width, iris)
tidy.lm <- function(x, conf.int = FALSE, conf.level = 0.95, n=TRUE, ...) {
  
  # error on inappropriate subclassing
  # TODO: undo gee / mclogit and other catches
  if (length(class(x)) > 1) {
    stop("No tidy method for objects of class ", class(x)[1], call. = FALSE)
  }
  
  ret <- as_tibble(summary(x)$coefficients, rownames = "term")
  colnames(ret) <- c("term", "estimate", "std.error", "statistic", "p.value", "n")
  
  # summary(x)$coefficients misses rank deficient rows (i.e. coefs that
  # summary.lm() sets to NA), catch them here and add them back
  coefs <- tibble::enframe(stats::coef(x), name = "term", value = "estimate")
  ret <- left_join(coefs, ret, by = c("term", "estimate"))
  
  if (conf.int) {
    ci <- broom_confint_terms(x, level = conf.level)
    ret <- dplyr::left_join(ret, ci, by = "term")
  }
  if (n) {
    ret$n <- length(x$residuals) 
  }
  
  ret
}
tidy(fit)
```

**Comment by simonpcouch** [comment]
Thanks for the issue! 

In this example, `n` is describing model-level characteristics, which are the domain of `glance.*()` methods, rather than component-level (i.e. each regression coef) characteristics, which are what `tidy.*()` methods are intended for. This is why, in your example, the `n` entry is repeated for each coefficient. The `nobs` column in `glance(fit)` (in the development version of the package) gives you what you're looking for.🙂

**Comment by lrose1** [comment]
Ah yes I didn't see that in the development version. Thanks for implementing!
