### ISSUE TITLE
tidy(ivreg, instruments = TRUE) fails with dummy variable controls

### ISSUE THREAD

**Issue by hughjonesd** [tidymodels/broom#905]
Here's a minimal reprex that shows the problem:

```r
library(broom)
library(AER)
dfr <- data.frame(y = rnorm(50), a = rep(letters[1:5], 10), b = rnorm(50), d = rnorm(50))
mod <- ivreg(y ~ b + factor(a) | d + factor(a), data = dfr)
tidy(mod, instruments = TRUE)
```

This fails with

```
Error: New columns must be compatible with `.data`.
x New column has 5 rows.
ℹ `.data` has 1 row.
Run `rlang::last_error()` to see where the error occurred.
```

and presumably should return a row for each value of `factor(a)`.

**Comment by simonpcouch** [comment]
Haven't been able to track down a good fix for this quite yet, and I'm not sure whether it should come from broom, but a reprex showing some strange behavior:

``` r
library(broom)
library(AER)
#> Loading required package: car
#> Loading required package: carData
#> Loading required package: lmtest
#> Loading required package: zoo
#> 
#> Attaching package: 'zoo'
#> The following objects are masked from 'package:base':
#> 
#>     as.Date, as.Date.numeric
#> Loading required package: sandwich
#> Loading required package: survival

dfr <- data.frame(y = rnorm(50), a = rep(letters[1:5], 10), b = rnorm(50), d = rnorm(50))

mod <- ivreg(y ~ b + factor(a) | d + factor(a), data = dfr)
mod2 <- ivreg(y ~ b | factor(a) + d, data = dfr)
mod3 <- ivreg(y ~ b + factor(a) | d, data = dfr)
#> Warning in ivreg.fit(X, Y, Z, weights, offset, ...): more regressors than
#> instruments

tidy(mod, instruments = TRUE)
#> Error: New columns must be compatible with `.data`.
#> x New column has 5 rows.
#> ℹ `.data` has 1 row.
#> Backtrace:
#>     █
#>  1. ├─generics::tidy(mod, instruments = TRUE)
#>  2. └─broom:::tidy.ivreg(mod, instruments = TRUE)
#>  3.   ├─`%>%`(...)
#>  4.   │ └─base::eval(lhs, parent, parent)
#>  5.   │   └─base::eval(lhs, parent, parent)
#>  6.   └─tibble::add_column(d, term = end_vars, .before = TRUE)
tidy(mod2, instruments = TRUE)
#> # A tibble: 1 x 5
#>   term  num.df den.df statistic p.value
#>   <chr>  <dbl>  <dbl>     <dbl>   <dbl>
#> 1 b          5     44     0.986   0.437
tidy(mod3, instruments = TRUE)
#> # A tibble: 5 x 5
#>   term       num.df den.df statistic p.value
#>   <chr>       <dbl>  <dbl>     <dbl>   <dbl>
#> 1 b               1     48     1.17   0.284 
#> 2 factor(a)b      1     48     2.55   0.117 
#> 3 factor(a)c      1     48     2.03   0.160 
#> 4 factor(a)d      1     48     2.99   0.0904
#> 5 factor(a)e      1     48     0.702  0.406
```

<sup>Created on 2020-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

The tidiers work okay in a situation that, given the warning (when generating `mod3`, maybe they shouldn't? Not familiar with this model type, but thoughts on expected behavior would be much appreciated.

For reference, here's the relevant portion of the current source for the tidier when `instruments = TRUE`:

```
  end_vars <- names(coef(x))[-1] # subtract off the intercept
  d <- summary(x, diagnostics = TRUE)$diagnostics

  # drop last two rows, the Wu-Hausman and Sargan diagnostics
  last_two_rows <- c(nrow(d) - 1, nrow(d))
  d <- as_tibble(d)[-last_two_rows, ]
  tibble::add_column(d, term = end_vars, .before = TRUE) %>%
    rename2("p.value" = "p-value", "num.df" = "df1", "den.df" = "df2")
```

**Comment by vincentarelbundock** [comment]
I think the tidier is at fault here. The docs state that `instruments=TRUE` returns: 

> diagnostics tests for each endogenous regressor (F-statistics).

However, the `summary(x, diagnostics = TRUE)$diagnostics` object includes things like a weak instruments test and the Wu-Hausman test, which are model-wide tests, and not term-specific. One hint of that is that the tidier is trying to create columns for degrees of freedom: `df1` and `df2`.

In my view, those should probably go in `glance` instead of `tidy`. And in fact, they are *already* in `glance`:

https://github.com/tidymodels/broom/blob/master/R/aer-tidiers.R#L142

So I think the best course of action is simply to remove the `instruments` argument of this tidier. 

Of course, this does not fix the OP's problem if they want to extract features of the instrument stage of the 2SLS (at the term level). But after a bit of introspection on the `ivreg` object, I'm still not sure how to extract that information.
