### ISSUE TITLE
s3 dispatch and UseMethod

### ISSUE THREAD

**Issue by simonpcouch** [tidymodels/broom#948]
We've had a few issues recently about trouble with S3 dispatch for model objects that used to fall back to `tidy.lm()` (or other subclasses), but now error out with `No tidy method for objects of class ____`. 

Examples and reprexes on #939, #947.

Initially thought tidymodels/parsnip#291 might be related (thanks, @juliasilge!), but, ideally, we wouldn't actually be explicitly exporting / directing objects from packages currently not in `Imports` or `Suggests` to the `lm` tidier or others.

**Comment by alexpghayes** [comment]
This is behavior I special-cased into the implementation of tidy.lm() to be
stricter and avoid spooky behavior. I.e. after dispatch to tidy.lm(), if an
object has additional class attributes we know it isn't a real lm object
and we call tidy.default() on it to get a nice error message. If you have
an example of behavior that is surprising please let me know but I'm
convinced this is in general the right approach.

**Comment by simonpcouch** [comment]
Gotcha--was this first integrated into a CRAN version in 0.7.0, then? The two issues linked in the issue description show examples of the resulting behavior. Not sure if copying the function definition and exporting new tidiers is the way we want to go with this for tidiers that were previously supported via S3 dispatch, even if uninentional.

**Comment by alexpghayes** [comment]
> was this first integrated into a CRAN version in 0.7.0, then? 

I believe so.

> Not sure if copying the function definition and exporting new tidiers is the way we want to go with this for tidiers that were previously supported via S3 dispatch, even if unintentional.

So there's essential two kinds of errors to worry about with objects that subclass `lm`. The first is that the object is so different from `lm` objects that `tidy.lm()` just explodes. The second is that `tidy.lm()` works but gives the wrong result due to differences in the subclassed object and the implementation for the `lm` superclass. This is what I'm particularly motivated to avoid since it would take an act of god to detect bugs like this but they could lead to things like reporting bad estimates in papers.

Copy-pasting the `tidy.lm()` method merely creates a new problem. In general, copy-pasting tidiers leads to weird special cases in the `tidy.lm_subclass()` code that only matters for real `lm` objects and it extremely confusing down the line to maintain. Having dealt with this about a bajillion times I'm convinced the correct solution is to write new tidiers from scratch. The downside is this breaks existing user code. The upside is that we avoid the extremely bad silent reporting bugs no one will catch.

**Comment by alexpghayes** [comment]
As a side note this same discussion came up when Joyce was writing `butcher` and Hadley and Max basically came down on the "support fake `lm` objects" side of things for convenience and I basically said (and still strongly) believe this is not justifiable from a correctness point of view. This is in large part because it is extremely common in my opinion for researchers copy-paste an `lm` implementation and swap out a few limited parts to fit their use case and not check that their changes are compatible with all the other (frequency used) `lm` machinery.

I have some thoughts about more appropriate design patterns here to guarantee correctness but I don't think they really apply to `broom` use case nicely enough to be worth implementing.

**Comment by simonpcouch** [comment]
That context is really, really helpful. Much appreciated!

Will keep this in mind addressing these sorts of issues here on out. Might mock up a blog post / gist to clarify those points as well.

**Comment by alexpghayes** [comment]
@simonpcouch There's a `butcher` issue somewhere (perhaps in a pre-`butcher`) package actually when I wrote up some examples and the reasoning behind them. @jyuu might have deleted the repo though?

Anyway, I'd ask you to hold off on posting anything too publicly about this pattern without some sort of coordination. I think there's an OOP argument here that deserves being made carefully, and that it could pretty easily be dismissed too early if we don't make it well. I've been thinking about writing this pattern and several others (i.e. patterns related to the `lmtest` package) in a short JSS paper. I'd love to brainstorm more about this, perhaps in Slack?
